workflows:
  android-debug-all:
    name: Both Flavors Debug
    max_build_duration: 45
    environment:
      java: 17
    scripts:
      - name: Generate gradle-wrapper.jar
        script: gradle wrapper --gradle-version=8.11.1

      - name: Set gradlew executable
        script: chmod +x gradlew

      - name: Build Auto Debug APK
        script: ./gradlew assembleAutoDebug --stacktrace

      - name: Build Manual Debug APK
        script: ./gradlew assembleManualDebug --stacktrace

    artifacts:
      - app/build/outputs/apk/auto/debug/*.apk
      - app/build/outputs/apk/manual/debug/*.apk
